# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

GameRetailer.create(name: 'Amazon', website: 'http://www.amazon.com/')
GameRetailer.create(name: 'App Store', website: 'http://www.apple.com/iphone/from-the-app-store/')
GameRetailer.create(name: 'Best Buy', website: 'http://www.bestbuy.com/')
GameRetailer.create(name: 'EB Games', website: 'http://www.ebgames.com/')
GameRetailer.create(name: 'GameStop', website: 'http://www.gamestop.com/')
GameRetailer.create(name: 'Google Play', website: 'https://play.google.com/store')
GameRetailer.create(name: 'Nintendo eShop', website: 'http://www.nintendo.com/3ds/downloads/')
GameRetailer.create(name: 'PlayStation Store', website: 'http://us.playstation.com/psn/playstation-store/')
GameRetailer.create(name: 'Steam', website: 'http://store.steampowered.com/')
GameRetailer.create(name: 'Target', website: 'http://www.target.com/')
GameRetailer.create(name: 'Toys R Us', website: 'http://www.toysrus.com/')
GameRetailer.create(name: 'Walmart', website: 'http://www.walmart.com/')
GameRetailer.create(name: 'Xbox Live Marketplace', website: 'http://marketplace.xbox.com/')

Platform.create(name: 'Android', manufacturer: 'Google', image_url: 'platforms/Android.png')
Platform.create(name: 'iOS', manufacturer: 'Apple', image_url: 'platforms/iOS.png')
Platform.create(name: 'Mac', manufacturer: 'Apple', image_url: 'platforms/Mac.jpg')
Platform.create(name: 'Nintendo 3DS', release_date: '2011-03-27', manufacturer: 'Nintendo', image_url: 'platforms/Nintendo_3DS.png')
Platform.create(name: 'Nintendo DS', release_date: '2004-11-21', manufacturer: 'Nintendo', image_url: 'platforms/Nintendo_DS.png')
Platform.create(name: 'PC', manufacturer: 'Microsoft', image_url: 'platforms/PC.png')
Platform.create(name: 'PlayStation 3', release_date: '2006-11-11', manufacturer: 'Sony', image_url: 'platforms/PlayStation_3.png')
Platform.create(name: 'PlayStation Vita', release_date: '2012-02-22', manufacturer: 'Sony', image_url: 'platforms/PlayStation_Vita.png')
Platform.create(name: 'Wii', release_date: '2006-11-19', manufacturer: 'Nintendo', image_url: 'platforms/Wii.png')
Platform.create(name: 'Wii U', release_date: '2012-11-18', manufacturer: 'Nintendo', image_url: 'platforms/Wii_U.png')
Platform.create(name: 'Xbox 360', release_date: '2005-11-22', manufacturer: 'Microsoft', image_url: 'platforms/Xbox_360.png')

Game.create(title: 'Alan Wake', genre: 'Third-Person Shooter', developer: 'Remedy Entertainment', publisher: 'Microsoft Game Studios', release_date: '2010-05-18', image_url: 'games/Alan_Wake.jpg')
Game.create(title: 'Angry Birds', genre: 'Puzzle', developer: 'Rovio Entertainment', publisher: 'Rovio Entertainment', release_date: '2009-12-11', image_url: 'games/Angry_Birds.png')
Game.create(title: 'Angry Birds Rio', genre: 'Puzzle', developer: 'Rovio Entertainment', publisher: 'Rovio Entertainment', release_date: '2011-03-22', image_url: 'games/Angry_Birds_Rio.png')
Game.create(title: 'Angry Birds Seasons', genre: 'Puzzle', developer: 'Rovio Entertainment', publisher: 'Rovio Entertainment', release_date: '2010-10-21', image_url: 'games/Angry_Birds_Seasons.png')
Game.create(title: 'Angry Birds Space', genre: 'Puzzle', developer: 'Rovio Entertainment', publisher: 'Rovio Entertainment', release_date: '2012-03-22', image_url: 'games/Angry_Birds_Space.jpg')
Game.create(title: 'Angry Birds Star Wars', genre: 'Puzzle', developer: 'Rovio Entertainment', publisher: 'Rovio Entertainment', release_date: '2012-11-08', image_url: 'games/Angry_Birds_Star_Wars.png')
Game.create(title: 'Assassin\'s Creed II', genre: 'Action Adventure', developer: 'Ubisoft Montreal', publisher: 'Ubisoft', release_date: '2009-11-17', image_url: 'games/Assassins_Creed_2.jpg')
Game.create(title: 'Batman: Arkham Asylum', genre: 'Action Adventure', developer: 'Rocksteady Studios', publisher: 'Warner Bros. Interactive', release_date: '2009-08-25', image_url: 'games/Batman_Arkham_Asylum.jpg')
Game.create(title: 'Batman: Arkham City', genre: 'Action Adventure', developer: 'Rocksteady Studios', publisher: 'Warner Bros. Interactive', release_date: '2011-10-18', image_url: 'games/Batman_Arkham_City.jpg')
Game.create(title: 'Battlefield 3', genre: 'First-Person Shooter', developer: 'DICE', publisher: 'Electronic Arts', release_date: '2011-10-25', image_url: 'games/Battlefield_3.jpg')
Game.create(title: 'BioShock', genre: 'First-Person Shooter', developer: '2K Boston', publisher: '2K Games', release_date: '2007-08-21', image_url: 'games/BioShock.jpg')
Game.create(title: 'BioShock 2', genre: 'First-Person Shooter', developer: '2K Marin', publisher: '2K Games', release_date: '2010-02-09', image_url: 'games/BioShock_2.jpg')
Game.create(title: 'Borderlands', genre: 'First-Person Shooter', developer: 'Gearbox Software', publisher: '2K Games', release_date: '2009-10-20', image_url: 'games/Borderlands.jpg')
Game.create(title: 'Borderlands 2', genre: 'First-Person Shooter', developer: 'Gearbox Software', publisher: '2K Games', release_date: '2012-09-18', image_url: 'games/Borderlands_2.jpg')
Game.create(title: 'Call of Duty 2', genre: 'First-Person Shooter', developer: 'Infinity Ward', publisher: 'Activision', release_date: '2005-11-17', image_url: 'games/Call_of_Duty_2.jpg')
Game.create(title: 'Call of Duty 3', genre: 'First-Person Shooter', developer: 'Treyarch', publisher: 'Activision', release_date: '2006-11-07', image_url: 'games/Call_of_Duty_3.jpg')
Game.create(title: 'Call of Duty 4: Modern Warfare', genre: 'First-Person Shooter', developer: 'Infinity Ward', publisher: 'Activision', release_date: '2007-11-05', image_url: 'games/Call_of_Duty_4_Modern_Warfare.jpg')
Game.create(title: 'Call of Duty: Black Ops', genre: 'First-Person Shooter', developer: 'Treyarch', publisher: 'Activision', release_date: '2010-11-10', image_url: 'games/Call_of_Duty_Black_Ops.png')
Game.create(title: 'Call of Duty: Black Ops II', genre: 'First-Person Shooter', developer: 'Treyarch', publisher: 'Activision', release_date: '2012-11-13', image_url: 'games/Call_of_Duty_Black_Ops_II.png')
Game.create(title: 'Call of Duty: Modern Warfare 2', genre: 'First-Person Shooter', developer: 'Infinity Ward', publisher: 'Activision', release_date: '2009-11-10', image_url: 'games/Call_of_Duty_Modern_Warfare_2.PNG')
Game.create(title: 'Call of Duty: Modern Warfare 3', genre: 'First-Person Shooter', developer: 'Infinity Ward', publisher: 'Activision', release_date: '2011-11-08', image_url: 'games/Call_of_Duty_Modern_Warfare_3.png')
Game.create(title: 'Call of Duty: World at War', genre: 'First-Person Shooter', developer: 'Treyarch', publisher: 'Activision', release_date: '2008-11-11', image_url: 'games/Call_of_Duty_World_at_War.png')
Game.create(title: 'Crysis', genre: 'First-Person Shooter', developer: 'Crytek', publisher: 'EA Games', release_date: '2007-11-13', image_url: 'games/Crysis.jpg')
Game.create(title: 'Crysis 2', genre: 'First-Person Shooter', developer: 'Crytek', publisher: 'EA Games', release_date: '2011-03-22', image_url: 'games/Crysis_2.png')
Game.create(title: 'Cut The Rope', genre: 'Puzzle', developer: 'ZeptoLab', publisher: 'ZeptoLab', release_date: '2011-08-04', image_url: 'games/Cut_the_Rope.png')
Game.create(title: 'Dance Central 2', genre: 'Music', developer: 'Harmonix Music Systems', publisher: 'Harmonix Music Systems', release_date: '2011-10-25', image_url: 'games/Dance_Central_2.jpg')
Game.create(title: 'Dark Souls', genre: 'Action RPG', developer: 'From Software', publisher: 'Namco Bandai Games', release_date: '2011-10-04', image_url: 'games/Dark_Souls.jpg')
Game.create(title: 'Dead Space 2', genre: 'Third-Person Shooter', developer: 'Visceral Games', publisher: 'Electronic Arts', release_date: '2011-01-25', image_url: 'games/Dead_Space_2.jpg')
Game.create(title: 'Deus Ex: Human Revolution', genre: 'Action RPG', developer: 'Eidos Montreal', publisher: 'Square Enix', release_date: '2011-08-23', image_url: 'games/Deus_Ex_Human_Revolution.jpg')
Game.create(title: 'Diablo II', genre: 'Action RPG', developer: 'Blizzard North', publisher: 'Blizzard Entertainment', release_date: '2000-06-29', image_url: 'games/Diablo_II.png')
Game.create(title: 'Diablo III', genre: 'Action RPG', developer: 'Blizzard Entertainment', publisher: 'Blizzard Entertainment', release_date: '2012-05-15', image_url: 'games/Diablo_III.png')
Game.create(title: 'Dishonored', genre: 'Action Adventure', developer: 'Arkane Studios', publisher: 'Bethesda Softworks', release_date: '2012-10-09', image_url: 'games/Dishonored.jpg')
Game.create(title: 'Donkey Kong Country Returns', genre: 'Platform', developer: 'Retro Studios', publisher: 'Nintendo', release_date: '2010-11-21', image_url: 'games/Donkey_Kong_Country_Returns.jpg')
Game.create(title: 'F1 2012', genre: 'Racing', developer: 'Codemasters Birmingham', publisher: 'Codemasters', release_date: '2012-09-18', image_url: 'games/F1_2012.png')
Game.create(title: 'Fallout 3', genre: 'Action RPG', developer: 'Bethesda Game Studios', publisher: 'Bethesda Softworks', release_date: '2008-10-28', image_url: 'games/Fallout_3.png')
Game.create(title: 'Far Cry 3', genre: 'First-Person Shooter', developer: 'Ubisoft Montreal', publisher: 'Ubisoft', release_date: '2012-12-04', image_url: 'games/Far_Cry_3.jpg')
Game.create(title: 'Fez', genre: 'Platform', developer: 'Polytron', publisher: 'Trapdoor', release_date: '2012-04-13', image_url: 'games/Fez.png')
Game.create(title: 'FIFA Soccer 12', genre: 'Sports', developer: 'EA Canada', publisher: 'Electronic Arts', release_date: '2011-09-27', image_url: 'games/FIFA_12.jpg')
Game.create(title: 'FIFA Soccer 13', genre: 'Sports', developer: 'EA Canada', publisher: 'Electronic Arts', release_date: '2012-09-25', image_url: 'games/FIFA_13.jpeg')
Game.create(title: 'Gears of War', genre: 'Third-Person Shooter', developer: 'Epic Games', publisher: 'Microsoft Game Studios', release_date: '26-11-07', image_url: 'games/Gears_of_War.png')
Game.create(title: 'Gears of War 2', genre: 'Third-Person Shooter', developer: 'Epic Games', publisher: 'Microsoft Game Studios', release_date: '2008-11-07', image_url: 'games/Gears_of_War_2.jpg')
Game.create(title: 'Gears of War 3', genre: 'Third-Person Shooter', developer: 'Epic Games', publisher: 'Microsoft Studios', release_date: '2011-09-20', image_url: 'games/Gears_of_War_3.png')
Game.create(title: 'Grand Theft Auto IV', genre: 'Action Adventure', developer: 'Rockstar North', publisher: 'Rockstar Games', release_date: '2008-04-29', image_url: 'games/Grand_Theft_Auto_IV.jpg')
Game.create(title: 'Halo 3', genre: 'First-Person Shooter', developer: 'Bungie', publisher: 'Microsoft Game Studios', release_date: '2007-09-25', image_url: 'games/Halo_3.JPG')
Game.create(title: 'Halo 3: ODST', genre: 'First-Person Shooter', developer: 'Bungie', publisher: 'Microsoft Game Studios', release_date: '2009-09-22', image_url: 'games/Halo_3_ODST.png')
Game.create(title: 'Halo 4', genre: 'First-Person Shooter', developer: '343 Industries', publisher: 'Microsoft Studios', release_date: '2012-11-06', image_url: 'games/Halo_4.png')
Game.create(title: 'Halo: Reach', genre: 'First-Person Shooter', developer: 'Bungie', publisher: 'Microsoft Game Studios', release_date: '2010-09-14', image_url: 'games/Halo_Reach.png')
Game.create(title: 'Mass Effect', genre: 'Action RPG', developer: 'BioWare', publisher: 'Microsoft Game Studios', release_date: '2007-11-20', image_url: 'games/Mass_Effect.jpg')
Game.create(title: 'Mass Effect 2', genre: 'Action RPG', developer: 'BioWare', publisher: 'Electronic Arts', release_date: '2010-01-26', image_url: 'games/Mass_Effect_2.png')
Game.create(title: 'Mass Effect 3', genre: 'Action RPG', developer: 'BioWare', publisher: 'Electronic Arts', release_date: '2012-03-06', image_url: 'games/Mass_Effect_3.jpg')
Game.create(title: 'Red Dead Redemption', genre: 'Action Adventure', developer: 'Rockstar San Diego', publisher: 'Rockstar Games', release_date: '2010-05-18', image_url: 'games/Red_Dead_Redemption.jpg')
Game.create(title: 'The Elder Scrolls V: Skyrim', genre: 'Action RPG', developer: 'Bethesda Game Studios', publisher: 'Bethesda Softworks', release_date: '2011-11-11', image_url: 'games/The_Elder_Scrolls_V_Skyrim.png')

GamePlatform.create(game: Game.find_by_title('Alan Wake'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Alan Wake'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Angry Birds'), platform: Platform.find_by_name('Android'))
GamePlatform.create(game: Game.find_by_title('Angry Birds'), platform: Platform.find_by_name('iOS'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Rio'), platform: Platform.find_by_name('Android'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Rio'), platform: Platform.find_by_name('iOS'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Rio'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Rio'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Seasons'), platform: Platform.find_by_name('Android'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Seasons'), platform: Platform.find_by_name('iOS'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Seasons'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Seasons'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Space'), platform: Platform.find_by_name('Android'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Space'), platform: Platform.find_by_name('iOS'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Space'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Space'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Star Wars'), platform: Platform.find_by_name('Android'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Star Wars'), platform: Platform.find_by_name('iOS'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Star Wars'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Angry Birds Star Wars'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Assassin\'s Creed II'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Assassin\'s Creed II'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Assassin\'s Creed II'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Assassin\'s Creed II'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Batman: Arkham Asylum'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Batman: Arkham Asylum'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Batman: Arkham Asylum'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Batman: Arkham Asylum'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Batman: Arkham City'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Batman: Arkham City'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Batman: Arkham City'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Batman: Arkham City'), platform: Platform.find_by_name('Wii U'))
GamePlatform.create(game: Game.find_by_title('Batman: Arkham City'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Battlefield 3'), platform: Platform.find_by_name('iOS'))
GamePlatform.create(game: Game.find_by_title('Battlefield 3'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Battlefield 3'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Battlefield 3'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('BioShock'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('BioShock'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('BioShock'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('BioShock'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('BioShock 2'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('BioShock 2'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('BioShock 2'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('BioShock 2'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Borderlands'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Borderlands'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Borderlands'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Borderlands'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Borderlands 2'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Borderlands 2'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Borderlands 2'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Borderlands 2'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Call of Duty 2'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Call of Duty 2'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Call of Duty 2'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Call of Duty 3'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Call of Duty 3'), platform: Platform.find_by_name('Wii'))
GamePlatform.create(game: Game.find_by_title('Call of Duty 3'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Call of Duty 4: Modern Warfare'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Call of Duty 4: Modern Warfare'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Call of Duty 4: Modern Warfare'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Call of Duty 4: Modern Warfare'), platform: Platform.find_by_name('Wii'))
GamePlatform.create(game: Game.find_by_title('Call of Duty 4: Modern Warfare'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Black Ops'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Black Ops'), platform: Platform.find_by_name('Nintendo DS'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Black Ops'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Black Ops'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Black Ops'), platform: Platform.find_by_name('Wii'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Black Ops'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Black Ops II'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Black Ops II'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Black Ops II'), platform: Platform.find_by_name('Wii U'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Black Ops II'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Modern Warfare 2'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Modern Warfare 2'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Modern Warfare 2'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Modern Warfare 3'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Modern Warfare 3'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Modern Warfare 3'), platform: Platform.find_by_name('Wii'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: Modern Warfare 3'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: World at War'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: World at War'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: World at War'), platform: Platform.find_by_name('Wii'))
GamePlatform.create(game: Game.find_by_title('Call of Duty: World at War'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Crysis'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Crysis'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Crysis'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Crysis 2'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Crysis 2'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Crysis 2'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Cut The Rope'), platform: Platform.find_by_name('Android'))
GamePlatform.create(game: Game.find_by_title('Cut The Rope'), platform: Platform.find_by_name('iOS'))
GamePlatform.create(game: Game.find_by_title('Dance Central 2'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Dark Souls'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Dark Souls'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Dark Souls'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Dead Space 2'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Dead Space 2'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Dead Space 2'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Deus Ex: Human Revolution'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Deus Ex: Human Revolution'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Deus Ex: Human Revolution'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Deus Ex: Human Revolution'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Diablo II'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Diablo II'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Diablo III'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('Diablo III'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Dishonored'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Dishonored'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Dishonored'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Donkey Kong Country Returns'), platform: Platform.find_by_name('Wii'))
GamePlatform.create(game: Game.find_by_title('F1 2012'), platform: Platform.find_by_name('iOS'))
GamePlatform.create(game: Game.find_by_title('F1 2012'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('F1 2012'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('F1 2012'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('F1 2012'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Fallout 3'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Fallout 3'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Fallout 3'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Far Cry 3'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Far Cry 3'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Far Cry 3'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Fez'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 12'), platform: Platform.find_by_name('Android'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 12'), platform: Platform.find_by_name('iOS'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 12'), platform: Platform.find_by_name('Nintendo 3DS'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 12'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 12'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 12'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 12'), platform: Platform.find_by_name('Wii'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 12'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 13'), platform: Platform.find_by_name('Android'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 13'), platform: Platform.find_by_name('iOS'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 13'), platform: Platform.find_by_name('Nintendo 3DS'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 13'), platform: Platform.find_by_name('Mac'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 13'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 13'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 13'), platform: Platform.find_by_name('PlayStation Vita'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 13'), platform: Platform.find_by_name('Wii'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 13'), platform: Platform.find_by_name('Wii U'))
GamePlatform.create(game: Game.find_by_title('FIFA Soccer 13'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Gears of War'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Gears of War'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Gears of War 2'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Gears of War 3'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Grand Theft Auto IV'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Grand Theft Auto IV'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Grand Theft Auto IV'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Halo 3'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Halo 3: ODST'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Halo 4'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Halo: Reach'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Mass Effect'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Mass Effect'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Mass Effect'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Mass Effect 2'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Mass Effect 2'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Mass Effect 2'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Mass Effect 3'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('Mass Effect 3'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Mass Effect 3'), platform: Platform.find_by_name('Wii U'))
GamePlatform.create(game: Game.find_by_title('Mass Effect 3'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('Red Dead Redemption'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('Red Dead Redemption'), platform: Platform.find_by_name('Xbox 360'))
GamePlatform.create(game: Game.find_by_title('The Elder Scrolls V: Skyrim'), platform: Platform.find_by_name('PC'))
GamePlatform.create(game: Game.find_by_title('The Elder Scrolls V: Skyrim'), platform: Platform.find_by_name('PlayStation 3'))
GamePlatform.create(game: Game.find_by_title('The Elder Scrolls V: Skyrim'), platform: Platform.find_by_name('Xbox 360'))